export class FoodInfo {
  id: string;
  code: number; /*抽单编号*/
  product: string; /*样品名称*/
  brand: string; /*商标*/
  entLeader: string; /*负责人*/
  packager: string; /*食品包装*/
  entPhone: string; /*被抽样企业联系人电话*/
  entLinkMan: string; /*被抽样单位联系人*/
  grade: string; /*质量等级*/
  place: string; /*产地*/
  licence: string; /*许可证编号*/
  deleted: string; /*删除状态*/
  qs: string; /*食品生产许可证*/
  orgId: string; /*用户识别状态*/
  missionResource: string; /*任务来源*/
  beSampleEnt: string; /*被抽样单位名称*/
  batch: string; /*样品批号*/
  sampleMan: string; /*抽样人员*/
  sampleDate: number; /*抽样日期*/
  sampleDateText: string;
  missionType: string; /*任务类别*/
  regionType: string; /*区域类型*/
  entAddress: string; /*被抽样单位地址*/
  type: string; /*规格*/
  license: string; /*营业执照*/
  entFax: string; /*被抽样企业传真*/
  sales: string; /*销售额*/
  entPostCode: string; /*被抽样企业邮编*/
  annualRing: string; /*生产环节*/
  circulation: string; /*流通环节*/
  catrringLink: string; /*餐饮环节*/
  area: string; /*检测区划分*/
  cirInfo: string; /*流通环节其他*/
  server: string; /*餐饮服务经营者*/
  cateen: string; /*单位食堂*/
  catInfo: string; /*餐饮环节其他*/
  sampleResource: string; /*样品来源*/
  sampleProperty: string; /*样品属性*/
  sampleType: string; /*样品类型*/
  samtInfo: string; /*样品类型其他*/
  warranty: string; /*保质期*/
  gb: string; /*执行标准/技术文件名*/
  unitPrice: string; /*单价*/
  sampleStage: string; /*样品日期类型*/
  stageDate: number; /*样品状态日期*/
  stageDateText: string;
  base: string; /*抽样基数/批量*/
  sampleNum: string; /*抽样数量*/
  sampleForm: string; /*样品形态*/
  exit: string; /*是否出口*/
  reserveNum: string; /*备样数量*/
  packageGroup: string; /*包装分类*/
  productOrg: string; /*生产企业名称*/
  productAddress: string; /*生产者地址*/
  productLinkMan: string; /*生产者联系人*/
  productPhone: string; /*生产者联系电话*/
  storageCondition: string; /*抽样时存储条件*/
  temperature: string; /*温度*/
  deadLine: number; /*寄送样品截止日期*/
  deadLineText: string;
  sendAddress: string; /*寄送样品地址*/
  sampleMold: string; /*抽样方式*/
  unitName: string; /*抽样单位名称*/
  unitAdress: string; /*抽样单位地址*/
  unitLinkMan: string; /*抽样单位联系人*/
  unitPhone: string; /*抽样单位电话*/
  unitFax: string; /*抽样单位传真*/
  unitPostCode: string; /*抽样单位邮编*/
  remark: string; /*抽样单位备注*/
  location: string; /*被抽样企业区划编码*/
  classify: string; /*产品类别编码*/
  unitCode: string; /*抽样单位编码*/
  odd: string; /*抽样编码（政府）*/
  hold: string; /*是否临时保存*/
  client: string; /*客户端*/
  year: number; /*年度*/
}
